FROM quay.io/jupyter/r-notebook:2024-12-03

RUN R -e "install.packages('tidyverse',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('nflfastR',dependencies=TRUE, repos='http://cran.rstudio.com/')"
